name: ResponseBot
version: 1.2.0
author: bittiez
main: US.bittiez.ResonseBot.main
commands:
    RB:
        description: /RB reload will reload the config file.
        usage: /RB reload
        permission: ResponseBot.reload
permissions:
    ResponseBot.reload:
        description: Allows the use of /RB reload